SELECT
  COD_ESTADISTICO AS SKU_A,
  COD_ESTADISTICO_TIA AS SKU_B,
  COD_SECCION AS SECTION_L0,
  NOM_SECCION AS SECTION_L0_NAME,
  COD_FAMILIA AS SECTION_L1,
  NOM_FAMILIA AS SECTION_L1_NAME,
  COD_SUBFAMILIA AS SECTION_L2,
  NOM_SUBFAMILIA AS SECTION_L2_NAME,
  NOM_PRODUCTO AS DESCRIPTION,
  TEMPORADA AS IS_SEASONAL,
  ES_MODA AS IS_FASHION,
  ES_PERECEDERO AS IS_PERISHABLE,
  UNID_EMPAQUE AS UNITS_PER_REP
FROM DW_ESTADISTICO_DIM
WHERE SKU_A IN [SELECTED_SKUS]
ORDER BY SECTION_L0, SECTION_L1, SECTION_L2, SKU_B;
