SELECT
  FECHA AS DATE_INV,
  COD_ESTADISTICO_TIA AS SKU_B,
  INV_AJUSTE
FROM DW_INVENTARIO
WHERE COD_SUCURSAL = [STORE-ID] AND
      SKU_A IN [PRESELECTED_SKUS]
ORDER BY SKU_B, DATE_INV;
ORDER BY SKU_B;
