WITH
TAB_L AS
(
	SELECT
		COD_ESTADISTICO AS SKU_A,
		COD_ESTADISTICO_TIA AS SKU_B
	FROM DW_ESTADISTICO_DIM
	WHERE FECHA_INTRODUCCION <= '[INTRO-YEAR-LIMIT]-12-31' AND
	      ES_PESABLE = 'N'
),
TAB_R AS
(
	SELECT DISTINCT
		FC_COD_ESTADISTICO AS SKU_A,
		FC_COD_ESTADISTICO_TIA AS SKU_B,
		FC_ES_EXCLUSION AS STATE_FLAG
	FROM DW_IPRODUCT_FACT
	WHERE FC_COD_SUCURSAL = [STORE-ID] AND
	      FC_COD_SECCION NOT IN ( 20, 38, 39)
)
SELECT
	TAB_L.SKU_A AS SKU_A,
	TAB_L.SKU_B AS SKU_B,
	TAB_R.STATE_FLAG AS STATE_FLAG
FROM TAB_L INNER JOIN TAB_R
ON TAB_L.SKU_A = TAB_R.SKU_A AND
   TAB_L.SKU_B = TAB_R.SKU_B
ORDER BY SKU_B;
